// vue-3-nuxt-supabase/components/anime/AnimeDetails.vue
<!-- eslint-disable vue/no-v-html -->
<template>
  <DefineTemplate v-slot="{ name, value }">
    <div class="space-x-1">
      <span
        class="text-base"
        :class="{ 'text-green-700': !props.animeData.isCool, 'text-yellow-700': props.animeData.isCool }"
      >
        {{ name }}
      </span>
      <span> {{ value ?? 0 }} </span>
    </div>
  </DefineTemplate>

  <article>
    <div class="flex gap-4 mb-2">
      <ReuseTemplate name="User" :value="props.animeData.user.name" />

      <div v-if="props.animeData.description" class="w-[2px] bg-gray-300"></div>

      <ReuseTemplate v-if="props.animeData.description" name="Description" :value="props.animeData.description" />
    </div>
    <div class="flex gap-4">
      <ReuseTemplate name="Episodes" :value="props.animeData.selectedAnime.episodes" />

      <div class="w-[2px] bg-gray-300"></div>

      <ReuseTemplate name="Score" :value="props.animeData.selectedAnime.score" />

      <div class="w-[2px] bg-gray-300"></div>

      <ReuseTemplate name="Duration" :value="props.animeData.selectedAnime.duration" />

      <div class="w-[2px] bg-gray-300"></div>

      <div>Equation: {{ hardMathEquationMemo(props.animeData.selectedAnime.score ?? 1) }}</div>
    </div>
  </article>
</template>

<script setup lang="ts">
import { AnimeTypeStore, hardMathEquationMemo } from '~/types';

const [DefineTemplate, ReuseTemplate] = createReusableTemplate<{ name: string; value?: string | number | null }>();

const props = defineProps<{
  animeData: AnimeTypeStore;
}>();
</script>

<style scoped></style>

// angular-signals/src/app/components/anime/anime-details.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { AnimeTypeStore } from '../../services/anime.service';
import { HardMathEquationPipe } from '../../pipes/hard-math-equation.pipe';

@Component({
	selector: 'app-anime-details',
	standalone: true,
	imports: [CommonModule, HardMathEquationPipe],
	//changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		<ng-template #reuseTemplate let-data="passingData">
			<div class="space-x-1">
				<span
					class="text-base"
					[ngClass]="{
						'text-green-700': !animeData.isCool,
						'text-yellow-700': animeData.isCool
					}"
				>
					{{ data.name }}
				</span>
				<span> {{ data.value }} </span>
			</div>
		</ng-template>

		<article>
			<div class="flex gap-4 mb-2">
				<ng-container
					*ngTemplateOutlet="reuseTemplate; context: { passingData: { name: 'User', value: animeData.user.name } }"
				></ng-container>

				<div *ngIf="animeData.description" class="w-[2px] bg-gray-300"></div>

				<ng-container
					*ngTemplateOutlet="
						reuseTemplate;
						context: { passingData: { name: 'Description', value: animeData.description } }
					"
				></ng-container>
			</div>
			<div class="flex gap-4">
				<ng-container
					*ngTemplateOutlet="
						reuseTemplate;
						context: { passingData: { name: 'Episodes', value: animeData.selectedAnime.episodes } }
					"
				></ng-container>

				<div class="w-[2px] bg-gray-300"></div>

				<ng-container
					*ngTemplateOutlet="
						reuseTemplate;
						context: { passingData: { name: 'Score', value: animeData.selectedAnime.score } }
					"
				></ng-container>

				<div class="w-[2px] bg-gray-300"></div>

				<ng-container
					*ngTemplateOutlet="
						reuseTemplate;
						context: { passingData: { name: 'Duration', value: animeData.selectedAnime.duration } }
					"
				></ng-container>

				<div class="w-[2px] bg-gray-300"></div>

				<div>Equation: {{ animeData.selectedAnime.score | hardMathEquation }}</div>
			</div>
		</article>
	`,
})
export class AnimeDetailsComponent {
	@Input() animeData!: AnimeTypeStore;
}
