// vue-3-nuxt-supabase/components/shared/Banner.vue
<template>
  <div>
    <div
      v-display-for-time="{ seconds: bannerTime }"
      class="w-full p-4 text-xl text-center text-white bg-red-500"
      @remainingTime="bannerTimeRef--"
    >
      Remaining time for banner: {{ bannerTimeRef }}
    </div>
  </div>
</template>

<script setup lang="ts">
const props = defineProps({
  bannerTime: {
    type: Number,
    required: true,
    validator: (value: number) => value > 0
  }
});

const bannerTimeRef = ref(props.bannerTime);
</script>

<style scoped></style>

// angular-signals/src/app/components/shared/banner.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { HideAfterDirective } from '../../directives/hide-after.directive';

@Component({
	selector: 'app-banner',
	standalone: true,
	imports: [CommonModule, HideAfterDirective],
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		<div
			*hideAfter="bannerTime as time; let counter = counter"
			class="w-full p-4 text-xl text-center text-white bg-red-500"
		>
			Remaining time for banner: {{ counter }}
		</div>
	`,
})
export class BannerComponent {
	@Input({ required: true }) bannerTime!: number;
}
