// vue-3/src/components/views/NotFound.vue
<template>
  <div class="mt-[200px]">
    <div class="grid gap-10 place-content-center">
      <h1 class="text-3xl text-center text-red-400">Error page</h1>
      You can display the error locally here: {{ error }}
      <button class="bg-gray-300 general" @click="handleError">This will clear the error.</button>
    </div>
  </div>
</template>

<script setup lang="ts">
const router = useRouter();

defineProps({
  error: {
    type: Error,
    required: true
  }
});

const handleError = () => {
  router.push("/anime");
};
</script>

<style scoped></style>

// angular-signals/src/app/components/views/not-found.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { Router, RouterModule } from '@angular/router';
import { routerAnimation } from '../../animations/router-default';
import { StickyDirective } from '../../directives/sticky.directive';
import { BannerComponent } from '../shared/banner.component';

@Component({
	selector: 'app-main',
	standalone: true,
	imports: [CommonModule, RouterModule, BannerComponent, StickyDirective],
	changeDetection: ChangeDetectionStrategy.OnPush,
	animations: [routerAnimation],
	template: `
		<div class="mt-[200px]">
			<div class="grid gap-10 place-content-center">
				<h1 class="text-3xl text-center text-red-400">Error page</h1>
				You can display the error locally here
				<button class="bg-gray-300 general" (click)="handleError()">This will clear the error.</button>
			</div>
		</div>
	`,
})
export class NotFoundComponent {
	router = inject(Router);

	handleError() {
		this.router.navigate(['/anime']);
	}
}
